<?php
/**
 * This is the default template for the Advanced U.S. Taxes
 * element in the totals loop of the content-cart
 * template part. It was added by Advanced U.S. Taxes add-on.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package exchange-addon-advanced-us-taxes
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_checkout_before_advanced_us_taxes_element' ); ?>
<div class="cart-taxes cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_advanced_us_taxes_element' ); ?>
	<?php _e( 'Tax', 'LION' ) . _x( ':', 'Used in superwidget for taxes. eg Tax: ', 'LION' ); ?> <?php esc_attr_e( it_exchange_advanced_us_taxes_addon_get_taxes_for_checkout() ); ?>
	<?php do_action( 'it_exchange_super_widget_checkout_end_advanced_us_taxes_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_advanced_us_taxes_element' ); ?>