<?php
/**
 * This is the default template for the Easy U.S. Sales Taxes
 * element in the totals loop of the content-cart
 * template part. It was added by Easy U.S. Sales Taxes add-on.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package exchange-addon-easy-us-sales-taxes
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_checkout_before_easy_us_sales_taxes_element' ); ?>
<div class="cart-taxes cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_easy_us_sales_taxes_element' ); ?>
	<?php _e( 'Tax', 'LION' ) . _x( ':', 'Used in superwidget for taxes. eg Tax: ', 'LION' ); ?> <?php esc_attr_e( it_exchange_easy_us_sales_taxes_addon_get_taxes_for_cart() ); ?>
	<?php echo it_exchange_easy_us_sales_taxes_addon_exemptions(); ?>
	<?php do_action( 'it_exchange_super_widget_checkout_end_easy_us_sales_taxes_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_easy_us_sales_taxes_element' ); ?>
